//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpAttendance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeAttendanceDBEntities : DbContext
    {
        public EmployeeAttendanceDBEntities()
            : base("name=EmployeeAttendanceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approval> Approval { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<InOutDetails> InOutDetails { get; set; }
        public virtual DbSet<tblMst_Holiday> tblMst_Holiday { get; set; }
        public virtual DbSet<tblMst_InOutType> tblMst_InOutType { get; set; }
        public virtual DbSet<tblMst_PresentStatus> tblMst_PresentStatus { get; set; }
        public virtual DbSet<tblMst_Scheme> tblMst_Scheme { get; set; }
    }
}
