//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpAttendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMst_InOutType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMst_InOutType()
        {
            this.InOutDetails = new HashSet<InOutDetails>();
        }
    
        public int InOutTypeId { get; set; }
        public string InOut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOutDetails> InOutDetails { get; set; }
    }
}
